### ISSUE TITLE
Are Documentation or Examples of any kind available?

### ISSUE THREAD

**Issue by BenAHammond** [Core-Techs/Winscp.Extensions#1]
Pretty straightforward question. Trying to decide between this library and the officially supported ones.

**Comment by ronnieoverby** [comment]
Check out [SessionTests.cs](https://github.com/Core-Techs/Winscp.Extensions/blob/master/Winscp.Extensions.Tests/SessionTests.cs) and [UploadTests.cs](https://github.com/Core-Techs/Winscp.Extensions/blob/master/Winscp.Extensions.Tests/UploadTests.cs).

We have another SFTP library wrapper that we use instead of this one: [CoreTechs.Sftp.Client](https://github.com/Core-Techs/CoreTechs.Sftp.Client). Here's the [Nuget package](https://www.nuget.org/packages/CoreTechs.Sftp.Client/).

This other library wraps [SSH.NET](https://www.nuget.org/packages/SSH.NET/) and has been more reliable than WINSCP in our experience.
